### ISSUE TITLE
Потенциальная уязвимость 

### ISSUE THREAD

**Issue by macik** [Roffun/confirmtheright#1]
Плагин имеет ряд уязвимых мест:

1. нет проверки на пользователя, который производит заливку файла. Т.е. любой пользователь зарегистрированный в системе может залить свой файл (для проверки залил тебе на сайт файл test.html)
2. Переменная `$_SERVER['DOCUMENT_ROOT']` может содержать путь не совпадающий с корневым каталогом текущего веб-сайта.
3. (не уязвимость, но баг) файл `confirmtheright.functions.php` имеет внутри запись 
```php
require_once cot_incfile('confirmtheright','plug');
```
которая по логике должна его же и загружать.

**Comment by Roffun** [comment]
Ок , спасибо за тест, сейчас скорректирую.
p.s. у меня на сервере файл test.html  отсутствует

**Comment by macik** [comment]
На локальном сервере фокус прошел. На твоем тоже написало, что «ок».

**Comment by Roffun** [comment]
Написало, но физически не создало ?
для профиля ведь стоит условие:


    <tr>
        <td>{USERS_PROFILE_CONFIRMTHERIGHT1_TITLE} <small>( {PHP.cot_extrafields.cot_users.CONFIRMTHERIGHT1.field_variants} )</small></td>
        <td>{USERS_PROFILE_CONFIRMTHERIGHT1}</td>
    </tr>
    <tr>
        <td>{USERS_PROFILE_CONFIRMTHERIGHT2_TITLE} <small>( {PHP.cot_extrafields.cot_users.CONFIRMTHERIGHT2.field_variants} )</small></td>
        <td>{USERS_PROFILE_CONFIRMTHERIGHT2}</td>
    </tr>



С пунктом 1 и 3 решение ясно, а по 2 пункту , чем лучше воспользоваться ?   ведь нам для проверки нужен именно корень.

**Comment by Roffun** [comment]
Вариант точка слеш подойдет ?

./

**Comment by Roffun** [comment]
Пункт 2 и пункт 3 скорректировал, теперь думаю каким условием лучше пользователя проверять, в шаблоне проверка есть, в подробном описании указано, если плагин включен и usr.isadmin , тогда кнопки показывать, но думаю что действительно лучше сделать это при формировании тегов а не в шаблоне.

**Comment by macik** [comment]
Полагаться на проверку в шаблоне и отображение полей нельзя! 
Сама форма может быть подделана пользователем и даже, если нет полей, тебе на сервер могут придти доп. данные в POST запросе. 
Поэтому если ты их не фильтруешь, система может их обработать, как если бы эти поля были в форме (это особенно касается экстраполей, которые обрабатываются «автоматически»).

**Comment by Roffun** [comment]
А как же тогда фильтровать экстраполя созданные просто в админом с точки зрения пользователя ?
В моем случае плагин лишь создает поле. А  если предположить что плагина нет, и любой пользователь на своем сайте для профиля создал поле file и добавил в профиль ? 
получается что он таким образом сам себе уязвимость создает ?

**Comment by Roffun** [comment]
Каким способом лучше всего сделать проверку в данной ситуации, учитывая что физически плагин не участвует сам по себе в работе экстраполей, он их лишь создает при установке.
Повесить на какой-нибудь хук ?   тогда какой ?
profile.update.first   ?

**Comment by macik** [comment]
Загрузка файлов на сайт это в целом уязвимое место. В приложении к экстра-полям тем более.
Тут все зависит от того, куда будут писаться файлы, какие расширения разрешены и т.п.

Тут сценарий такой: ты создал экстра-поле «файл». Система ждет загрузки в него данных. Даже если ты не вывел пользователю поле для ввода, никто не мешает мне, как злоумышленнику, сымитировать у себя это поле и послать в него данные (свой файл). Система не зная была ли форма выведена, но полагая что экстра-поле есть, и есть необходимость обработки данных из него — просто обработает мой файл, как если бы он был загружен мной в форму на сайте.

Более правильно с точки зрения безопасности: либо создать отдельную страницу с формой загрузки данных и собственным обработчиком, либо дополнить проверкой текущий код.

В твоем случае надо на `page.edit.update.first` и `page.add.add.first` повесить обработчик и проверять, кто нам посылает в этих полях данные. Если это не админ, обнулять соотв. переменные, иначе данные из них уйдут в систему и будут ей обработаны наравне с остальными.

**Comment by Roffun** [comment]
Почему page.edit.update.first и page.add.add.first  ?

Плагин создает поле только для Users , рассчитан для админа, и описание к нему именно на действия админа рассчитаны, http://cowr.info/articles/blog-internet/сonfirmtheright-plugin-cotonti
расширения файлов указаны только .txt и .html , файлы должны загружаться только в корень.
Смысл плагина - облегчить подтверждение прав для пользователя не умеющего работать с фтп.

Загрузил, подтвердил, удалил. 

Значит нужно проверять через хук :
profile.update.first

**Comment by Roffun** [comment]
Кстати в описании к плагину написано:

Для подтверждения права на сайт с помощью метатегов, рекомендую использовать плагин boxes под Cotonti, в котором эта возможность появилась в последнем обновлении, а подтверждение с помощью загрузки файла на сервер делать только при отсутствии вышеуказанного варианта, и для одноразовых подтверждений не требующих дальнейшего нахождения файла на сервере

**Comment by macik** [comment]
`profile.update.first` конечно. Это я в торопях...
(суть перед апдейтом данных).

**Comment by Roffun** [comment]
Ок, сделаю проверку

**Comment by Roffun** [comment]
Кстати нужно эту тему на форуме обсудить. Ведь если плагин ничего кроме создания экстраполей не делает, то получается что любое создание экстраполей это в принципе уязвимость?  почему тогда это нигде не помечено при создании ?

**Comment by Roffun** [comment]
Создал вчера тему на форуме по этому вопросу :+1: 
https://www.cotonti.com/forums?m=posts&q=8000&n=last#bottom

**Comment by macik** [comment]
В целом, это равнозначно созданию текстового поля без последующей проверки, что будет введено. Где-то прокатит, а где-то можем получить SQL инъекцию.

Вообще, зависит от того, какое поле и для какой части сайта создается, кто имеет доступ к этим полям. Например, если это для админской части, то риск ниже. Опять же, писать файлы программно в корень, это почти как стрелять себе в ногу. Представь я заливаю тебе в корень index.html, простор для фантазии огромен.

Как я писал выше программная заливка файлов это потенциальная дыра. Это одна из причин, почему в движке не реализован, например, онлайн редактор шаблонов.
Применительно к экстраполям типа файл — есть хуки `extrafields.import.file.first`, `extrafields.import.file.done` и `extrafields.movefiles`.

**Comment by Roffun** [comment]
Добавлена проверка, является ли пользователь админом

**Comment by macik** [comment]
Такой вариант не будет работать правильно по двум причинам:
1. Обработчик по `extrafields.import.file.first` общий для всех, поэтому другие экстра-поля типа файл могут пострадать из-за такой проверки. Надо проверять также имя поля 
2. `cot_error` создаст сообщение об ошибке и не даст данным быть записанными в БД, 
**но** файл все равно будет сохранен в системе, как если бы проверки не было. Надо принудительно обнулять входящие данные.

```
// примерный код
if (in_array($inputname, array('ruserCONFIRMTHERIGHT1', 'ruserCONFIRMTHERIGHT2')) && !$usr['isadmin'])
{
    cot_error($L['fileconfirmtheright_norights'], $inputname);
    unset($import);
}
```

**Comment by Roffun** [comment]
При таком варианте будет достаточно для контроля?

**Comment by macik** [comment]
Полагаю да.

**Comment by Roffun** [comment]
Правки внес, благодарю за участие
